# ===============================
# Hardware
# ===============================
CONFIG_NFCT_PINS_AS_GPIOS=y

# ===============================
# ZMK core / split
# ===============================
CONFIG_ZMK=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_CENTRAL=y

# ===============================
# Pointing / Mouse
# ===============================
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_SCROLL=y

# input-listener / runtime processors
CONFIG_ZMK_INPUT_LISTENER=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSORS=y

# ===============================
# Encoder (EC11)
# ===============================
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ===============================
# Volume (encoder用)
# ===============================
CONFIG_ZMK_VOLUME=y

# ===============================
# Battery / DYA Studio
# ===============================
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_HISTORY=y
CONFIG_ZMK_SETTINGS=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# ===============================
# Optional LED widget
# ===============================
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10